"""v0.3 fresh-repo skeleton initializer.

Assumes example-org/mono is EMPTY. Creates the full folder structure with
.gitkeep files, writes config.md with default values, creates life/*.md
skeletons, wiki/index.md header, MEMORY.md header, README.md welcome.

Does NOT migrate any content from example-org/mono. Start fresh.

Usage:
  python scripts/migrate_v0_3.py            # dry-run
  python scripts/migrate_v0_3.py --apply    # execute
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from monogram import github_store  # noqa: E402
from monogram.config import load_config  # noqa: E402


_DEFAULT_CONFIG_MD = """\
---
# Monogram configuration — edit freely, restart `monogram run` to apply.

primary_language: en

life_categories:
  - shopping
  - places
  - credentials
  - career
  - read-watch
  - meeting-notes
  - health
  - finance

never_read_paths:
  - life/credentials/
---

# Mono — Personal Data Vault

This is your Monogram data repository. Edit the YAML frontmatter above to
change your language or life categories. Restart `monogram run` to apply.

Categories:
- Add a category: append a line to `life_categories`. The next drop
  classified into it will auto-create `life/<name>.md`.
- Remove a category: delete the line. Existing file stays. Future drops
  fall back to `daily_only`.
- Rename: delete old, add new. Agent does NOT migrate existing file content.

The `credentials` entry is special. It writes to `life/credentials/`
(a subfolder) and the LLM is hard-blocked from reading that path.
Even if you remove `life/credentials/` from `never_read_paths`, the
code has a hardcoded `_HARD_NEVER_READ` tuple that cannot be overridden.
"""

_DEFAULT_README_MD = """\
# mono

Personal data vault maintained by [Monogram](https://github.com/example-org/monogram).

- `projects/` — active deadlined projects
- `life/` — ongoing life areas (config-driven)
- `wiki/` — flat knowledge base (tags in frontmatter)
- `daily/` — episodic drops + commits + daily reports
- `reports/weekly/` — weekly rollups
- `log/` — system telemetry (decisions, runs, unattributed)
- `MEMORY.md` — agent pointer index
- `board.md` — project board
- `config.md` — user-editable settings

Edit `config.md` to change your primary language or life categories.
"""

_DEFAULT_MEMORY_MD = """\
# MEMORY.md — mono repo pointer index

Updated by monogram on every pipeline run.

## Active projects

## Wiki — high-confidence

## Recent drops (last 7 days)
"""

_DEFAULT_BOARD_MD = """\
# Board — (empty)

## Active

## Inactive

## Done
"""

_DEFAULT_WIKI_INDEX = """\
# Wiki Index

One-line entry per wiki page. Auto-appended on every wiki write.
Regenerated by weekly lint (v0.3b).

"""

_LIFE_FILE_TEMPLATE = """\
# life/{name}

Append-only log of {name} entries. Latest at bottom.

"""

_CREDENTIAL_PLACEHOLDER = """\
# Credentials

This folder is NEVER READ by the LLM. Safe to store sensitive values here.

Individual captures go to `life/credentials/<slug>.md` as separate files.
This placeholder keeps the folder alive in git.

"""

_GITKEEP_DIRS = [
    "projects/archive",
    "log/runs",
    "reports/weekly",
    "daily",
]


def plan_writes() -> dict[str, str]:
    """Return path → content for the fresh-repo skeleton."""
    default_life_cats = [
        "shopping", "places", "career", "read-watch",
        "meeting-notes", "health", "finance",
    ]
    writes: dict[str, str] = {
        "config.md": _DEFAULT_CONFIG_MD,
        "README.md": _DEFAULT_README_MD,
        "MEMORY.md": _DEFAULT_MEMORY_MD,
        "board.md": _DEFAULT_BOARD_MD,
        "wiki/index.md": _DEFAULT_WIKI_INDEX,
        "life/credentials/credentials.md": _CREDENTIAL_PLACEHOLDER,
        "log/decisions.md": "# Decisions Log\n\n",
    }
    for cat in default_life_cats:
        writes[f"life/{cat}.md"] = _LIFE_FILE_TEMPLATE.format(name=cat)
    for d in _GITKEEP_DIRS:
        writes[f"{d}/.gitkeep"] = ""
    return writes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    cfg = load_config()
    print(f"Target repo: {cfg.github_repo}")
    if cfg.github_repo.endswith("/scheduler"):
        print("WARNING: repo ends with /scheduler — did you forget to update .env?")
        print("         Set GITHUB_REPO=example-org/mono (or your equivalent).")

    writes = plan_writes()
    print(f"\nPlanned writes: {len(writes)} files")
    for path in sorted(writes.keys()):
        size = len(writes[path])
        print(f"  {path:<50s} ({size} bytes)")

    if not args.apply:
        print("\nDry run. Re-run with --apply to execute.")
        return

    print("\nApplying...")
    ok = github_store.write_multi(writes, "monogram v0.3a: fresh skeleton init")
    print("Done." if ok else "Some writes failed — review output above.")


if __name__ == "__main__":
    main()
